---
fixtures:
  repositories:
    stdlib:
      repo: https://github.com/simp/puppetlabs-stdlib
      ref: 5.2.0
    # This needs to be in place for the rspec-puppet Hiera 5 hook to work
    # No idea why, it may be because Puppet sees a custom backend and loads all
    # of the global parts.
    compliance_markup:
      repo: "https://github.com/simp/pupmod-simp-compliance_markup"
      branch: "testing_hotfix_06062019"
  symlinks:
    simplib: "#{source_dir}"
